if(NOT DEFINED S3G_RNBO_ROOT)
  get_filename_component(S3G_RNBO_ROOT "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
endif()
file(READ "${S3G_RNBO_ROOT}/src/s3g_rnbo_vstgui.inc" gui)
file(READ "${S3G_RNBO_ROOT}/cmake/S3GRnboVSTGUI.cmake" build)
file(READ "${S3G_RNBO_ROOT}/src/s3g_rnbo_test_clap.cpp" core)
foreach(pattern "contentTop = 42" "panelX \\+ 16" "parametersPerPage = 24"
    "F::pluginTitleText" "drawHorizontalSlider" "GestureBegin" "GestureEnd"
    "endEdit" "runFileDialog" "portable::adjustSize" "param.defaultValue")
  if(NOT gui MATCHES "${pattern}")
    message(FATAL_ERROR "RNBO VSTGUI contract missing: ${pattern}")
  endif()
endforeach()
if(gui MATCHES "NSFont|NSOpenPanel|NSPopUpButton|0xf0f0f0|0xe8e8e8|Bold")
  message(FATAL_ERROR "Platform-specific or legacy bright/bold GUI drift")
endif()
foreach(pattern "FiraCode-Regular.ttf" "FiraCode-LICENSE.txt" "s3g_vstgui_foundation.cpp" "VSTGUI-LICENSE.txt")
  if(NOT build MATCHES "${pattern}")
    message(FATAL_ERROR "Missing shared resource contract: ${pattern}")
  endif()
endforeach()
if(NOT core MATCHES "CLAP_EXPORT const clap_plugin_entry_t clap_entry" OR
   NOT core MATCHES "static_cast<uint64_t>\\(n\\) > size")
  message(FATAL_ERROR "Missing portable entry export or bounded state stream")
endif()
if(DEFINED S3G_DSP_DIR AND EXISTS "${S3G_DSP_DIR}/plugins/common/s3g_vstgui_foundation.h")
  file(READ "${S3G_DSP_DIR}/plugins/common/s3g_vstgui_foundation.h" foundation)
  if(NOT foundation MATCHES "kMinimumEditorScale = 0.65" OR
     NOT foundation MATCHES "kMaximumEditorScale = 2.0")
    message(FATAL_ERROR "Review upstream editor scale contract")
  endif()
endif()
message(STATUS "RNBO shared VSTGUI style audit passed")
