# New timestamped directories only. Never replace a previous distribution.
foreach(required S3G_RNBO_MAC_BUILD S3G_RNBO_WINDOWS_BUILD S3G_RNBO_PACKAGE_ROOT S3G_RNBO_PACKAGE_SLUG S3G_RNBO_SOURCE_ROOT)
  if(NOT DEFINED ${required} OR "${${required}}" STREQUAL "")
    message(FATAL_ERROR "Missing ${required}")
  endif()
endforeach()
if(NOT S3G_RNBO_PACKAGE_SLUG MATCHES "^[A-Za-z0-9_][A-Za-z0-9_-]*$")
  message(FATAL_ERROR "Unsafe package slug")
endif()
set(bundle "s3g_${S3G_RNBO_PACKAGE_SLUG}.clap")
set(mac "${S3G_RNBO_MAC_BUILD}/${bundle}")
set(win "${S3G_RNBO_WINDOWS_BUILD}/${bundle}")
if(NOT IS_DIRECTORY "${mac}" OR NOT EXISTS "${mac}/Contents/Info.plist" OR
   NOT EXISTS "${win}" OR IS_DIRECTORY "${win}")
  message(FATAL_ERROR "Both completed CLAP artifacts are required")
endif()
foreach(platform MAC WINDOWS)
  set(root "${S3G_RNBO_${platform}_BUILD}")
  if(NOT EXISTS "${root}/rnbo-build-identity.txt")
    message(FATAL_ERROR "Missing build identity: ${root}")
  endif()
  file(READ "${root}/rnbo-build-identity.txt" identity_${platform})
endforeach()
if(NOT identity_MAC STREQUAL identity_WINDOWS)
  message(FATAL_ERROR "Mac and Windows export/metadata identities do not match")
endif()
file(READ "${win}" pe LIMIT 2 HEX)
if(NOT pe STREQUAL "4d5a")
  message(FATAL_ERROR "Windows CLAP is not a PE executable")
endif()
foreach(resource Fonts/FiraCode-Regular.ttf Fonts/FiraCode-LICENSE.txt Licenses/VSTGUI-LICENSE.txt Licenses/s3g-dsp-LICENSE.txt)
  if(NOT EXISTS "${mac}/Contents/Resources/${resource}" OR NOT EXISTS "${S3G_RNBO_WINDOWS_BUILD}/Resources/${resource}")
    message(FATAL_ERROR "Missing runtime resource: ${resource}")
  endif()
endforeach()
execute_process(COMMAND /usr/bin/codesign --verify --deep --strict "${mac}" COMMAND_ERROR_IS_FATAL ANY)
string(TIMESTAMP stamp "%Y%m%d-%H%M%S")
string(RANDOM LENGTH 6 ALPHABET 0123456789abcdef unique)
set(package "${S3G_RNBO_PACKAGE_ROOT}/s3g-rnbo-${S3G_RNBO_PACKAGE_SLUG}-mac-windows-${stamp}-${unique}")
if(EXISTS "${package}")
  message(FATAL_ERROR "Package destination already exists")
endif()
file(MAKE_DIRECTORY "${package}/macOS" "${package}/Windows")
execute_process(COMMAND /usr/bin/ditto --noqtn "${mac}" "${package}/macOS/${bundle}" COMMAND_ERROR_IS_FATAL ANY)
file(COPY "${win}" "${S3G_RNBO_WINDOWS_BUILD}/Resources" DESTINATION "${package}/Windows")
file(COPY "${S3G_RNBO_SOURCE_ROOT}/LICENSE" "${S3G_RNBO_SOURCE_ROOT}/THIRD_PARTY_NOTICES.md" DESTINATION "${package}")
file(COPY "${S3G_RNBO_MAC_BUILD}/rnbo-build-identity.txt" DESTINATION "${package}")
file(WRITE "${package}/README.txt"
  "RNBO CLAP test builds\n\nmacOS: copy the .clap bundle to your user CLAP folder.\nWindows x64: copy the .clap FILE and its entire adjacent Resources folder together into a CLAP scan folder. Do not copy only the .clap file.\n\nThese are CLAP plug-ins, not Max .mxo/.mxe64 externals.\nRNBO-generated source is not included or relicensed. See THIRD_PARTY_NOTICES.md.\nRestart REAPER before testing. Windows cross-building does not verify Windows host behavior.\n")
file(SHA256 "${win}" windows_hash)
file(WRITE "${package}/windows-sha256.txt" "${windows_hash}  ${bundle}\n")
message(STATUS "Mac + Windows package: ${package}")
